jummp-plugins/jummp-plugin-web-application/grails-app/controllers/net/biomodels/jummp/webapp/GotreeController.groovy
package net.biomodels.jummp.webapp

import grails.converters.JSON

/**
 * @short Controller to render the Gene Ontology Tree.
 *
 * @author Martin Gräßlin <m.graesslin@dkfz.de>
 */
class GotreeController {

    /**
     * Dependency Injection
     */
    def geneOntologyTreeService

    /**
     * Default action, just rendering the div where the JavaScript will create the tree.
     */
    def index = {
    }

    /**
     * Retrieves the next level from the core application and generates the nodes for the Dynatree jquery plugin.
     */
    def level = {
        def nodes
        if (!params.id || params.id == "0") {
            nodes = geneOntologyTreeService.treeLevel(-1L)
        } else {
            nodes = geneOntologyTreeService.treeLevel(params.id as Long)
        }
        List jsonNodes = []
        nodes.ontologies.each {
            String icon = null
            if (it.type) {
                switch (it.type) {
                case "IsA":
                    icon = "go_isa.gif"
                    break
                case "PartOf":
                    icon = "go_partof.gif"
                    break
                case "DevelopFrom":
                    icon = "go_devfrom.gif"
                    break
                case "Other":
                default:
                    icon = "go_other.gif"
                    break
                }
            }
            jsonNodes << [isLazy: true, title: "${it.identifier} - ${it.name}", goid: it.id, isFolder: true, icon: icon, key: "${it.id}"]
        }
        nodes.revisions.each {
            jsonNodes << [isLazy: false, title: it.model.name, modelId: it.model.id, revisionNumber: it.revisionNumber, isFolder: false]
        }
        if (jsonNodes.isEmpty()) {
            jsonNodes << [isLazy: false, title: "No Model found", isFolder: false]
        }
        render jsonNodes as JSON
    }

    /**
     * Searches Gene Ontologies for matching elements.
     **/
    def search = {
        List ontologies = geneOntologyTreeService.searchOntologies(params.id)
        List jsonElements = []
        ontologies.each {
            jsonElements << [
                value: "${it.description.identifier} - ${it.description.name}",
                id: it.id,
                goId: it.description.identifier,
                goTerm: it.description.name]
        }
        render jsonElements as JSON
    }

    /**
     * Provides the path of the gene ontology.
     **/
    def path = {
        Map data = [path: geneOntologyTreeService.findPath(params.id as Long)]
        render data as JSON
    }
}

jummp-plugins/jummp-plugin-web-application/grails-app/controllers/net/biomodels/jummp/webapp/SearchController.groovy
package net.biomodels.jummp.webapp

import grails.converters.JSON
import net.biomodels.jummp.core.model.ModelListSorting

class SearchController {
    /**
     * Dependency injection of modelService.
     **/
    def modelService
    /**
     * Dependency injection of modelHistoryService.
    **/
    def modelHistoryService

    def index = {
        redirect action: 'list'
    }

    /**
     * Default action showing a list view
     */
    def list = {
    }

    /**
     * Action returning the DataTable content as JSON
     */
    def dataTableSource = {
        int start = 0
        int length = 10
        if (params.iDisplayStart) {
            start = params.iDisplayStart as int
        }
        if (params.iDisplayLength) {
            length = Math.min(100, params.iDisplayLength as int)
        }
        def dataToRender = [:]
        dataToRender.sEcho = params.sEcho
        dataToRender.aaData = []

        dataToRender.iTotalRecords = modelService.getModelCount(params.sSearch)
        dataToRender.iTotalDisplayRecords = dataToRender.iTotalRecords
        dataToRender.offset = start
        dataToRender.iSortCol_0 = params.iSortCol_0
        dataToRender.sSortDir_0 = params.sSortDir_0

        ModelListSorting sort
        if (params.iSortCol_0 == null) {
            params.iSortCol_0 = 0
        }

        switch (params.iSortCol_0 as int) {
        case 1:
            sort = ModelListSorting.NAME
            break
        case 0: // id column is the default
        default:
            sort = ModelListSorting.ID
            break
        }

        List models = modelService.getAllModels(start, length, params.sSortDir_0 == "asc", sort, params.sSearch)
        models.each { model ->
            dataToRender.aaData << [
                model.id,
                model.name,
                model.publication
            ]
        }
        render dataToRender as JSON
    }

    def lastAccessedModels = {
        List data = modelHistoryService.history()
        def dataToRender = []
        data.each { model ->
            dataToRender << [id: model.id, name: model.name, submitter: model.submitter]
        }
        render dataToRender as JSON
    }
}

jummp-plugins/jummp-plugin-web-application/grails-app/views/search/list.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
    <head>
        <title>Model Listing</title>
        <meta name="layout" content="main" />
        <r:require module="showModels"/>
        <jqDT:resources/>
    </head>
    <body activetab="search">
        <table id="modelTable">
            <thead>
            <tr>
                <th><g:message code="model.list.modelId"/></th>
                <th><g:message code="model.list.name"/></th>
                <th><g:message code="model.list.publicationId"/></th>
            </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
            <tr>
                <th><g:message code="model.list.modelId"/></th>
                <th><g:message code="model.list.name"/></th>
                <th><g:message code="model.list.publicationId"/></th>
            </tr>
            </tfoot>
        </table>

    <r:script>
$(function() {
    $.jummp.showModels.loadModelList();
    $.jummp.showModels.lastAccessedModels($("#sidebar-element-last-accessed-models"));
});
    </r:script>
    </body>
    <content tag="sidebar">
        <div class="element" id="sidebar-element-last-accessed-models">
            <h1><g:message code="model.history.title"/></h1>
            <h2><g:message code="model.history.empty"/></h2>
            <p></p>
        </div>
        <div class="element">
            <h1>Gene Ontology Tree</h1>
            <h2>Browse models using GO Tree</h2>
            <p>This is a tree view of the models in this Database based on <a href="http://www.geneontology.org/">Gene Ontology</a>.</p>
            <p><g:link controller="gotree">link</g:link></p>
        </div>
    </content>
</html>